#!/bin/bash
STATE=`amixer get Master | egrep 'Playback.*?\[o' | egrep -o '\[o.+\]'`
echo $STATE
if [[ $STATE == '[on]' ]]; then
	amixer set Master toggle
else
	amixer set Master toggle &\
	amixer set Speaker toggle
fi
